<?php
    
    // Carrega a View Topo

    $this->loadView("index/topo");
    
?>

<div class="row-fluid">

    <?php if( Session::get("cadastro") ): ?>
    
        <div class="alert <?=Session::get("cadastro-class");?>">
            <?=Session::get("cadastro-msg");?>
        </div>
    
    <?php 
    
    // Remove as sessões
    Session::delete("cadastro");
    Session::delete("cadastro-class");
    Session::delete("cadastro-msg");   
    
    endif;
    
    ?>
        
    <form class="form-horizontal" method="post" action="<?=$urlAction;?>">
        <fieldset>
            
          <legend><?=$pageDesc;?></legend>            
            
          <div class="control-group">
            <label for="input-nome" class="control-label">Nome</label>
            <div class="controls">
                <input type="text" required value="<?=( isset($contato["nome"]) ) ? $contato["nome"] : "";?>" name="input-nome" class="input-xlarge focused">
            </div>
          </div>

          <div class="control-group">
            <label for="input-telefone" class="control-label">Telefone</label>
            <div class="controls">
                <input type="tel" required value="<?=( isset($contato["telefone"]) ) ? $contato["telefone"] : "";?>" name="input-telefone" class="input-xlarge">
            </div>
          </div>    
          
          <div class="control-group">
            <label for="input-celular" class="control-label">Celular</label>
            <div class="controls">
                <input type="tel" required value="<?=( isset($contato["celular"]) ) ? $contato["celular"] : "";?>" name="input-celular" class="input-xlarge">
            </div>
          </div>  
          
          <div class="control-group">
            <label for="input-email" class="control-label">E-mail</label>
            <div class="controls">
                <input type="email" required value="<?=( isset($contato["email"]) ) ? $contato["email"] : "";?>" name="input-email" class="input-xlarge">
            </div>
          </div>           
          
          <div class="form-actions">
            <button class="btn btn-primary" type="submit"><?=$submitDesc;?></button>
          </div>
          
        </fieldset>
      </form>


</div>

<?php
    
    // Carrega a View Rodapé

    $this->loadView("index/rodape");
    
?>